game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ALLA- TEKDIR !" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONDAN BASKA ILAH YOKTUR !" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")

loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()

game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("BYE" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")