game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ALLA- TEKDIR !" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONDAN BASKA ILAH YOKTUR !" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")

loadstring(game:HttpGet('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'))()

game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("BYE" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.8)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.3)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.5)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.4)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.6)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.2)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.5)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.4)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.3)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.2)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.3)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.1)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.2)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.4)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.3)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.5)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(1.5)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")
wait(2.2)
game.ReplicatedStorage.DefaultChatSystemChatEvents.SayMessageRequest:FireServer("ONUN NE ESI BENZERI NEDE BIR KOPYASI VARDIR !" ,"All")